export const tourDates = [
  {
    id: 1,
    venue: "The Camel",
    date: "2022-12-15",
    location: "Richmond, VA",
  },
  {
    id: 2,
    venue: "TV EYE",
    date: "2022-12-16",
    location: "Ridgewood, NY",
  },
  {
    id: 3,
    venue: "The NorVa",
    date: "2022-12-17",
    location: "Norfolk, VA",
  },
  {
    id: 4,
    venue: "Loose Cobra",
    date: "2024-08-17",
    location: "Tolono, IL (US)",
  },
  {
    id: 5,
    venue: "Mobious Records",
    date: "2024-08-24",
    location: "Washington, D.C. (US)",
  },
  {
    id: 6,
    venue: "Burgerhaus",
    date: "2024-10-18",
    location: "Bremen (DE)",
  },
  {
    id: 7,
    venue: "La Zone",
    date: "2024-10-19",
    location: "Liège (BE)",
  },
  {
    id: 8,
    venue: "villaWuller",
    date: "2024-10-20",
    location: "Trier (DE)",
  },
  {
    id: 9,
    venue: "La Source Beer Co.",
    date: "2024-10-22",
    location: "Brussels (BE)",
  },
  {
    id: 10,
    venue: "Supersonic",
    date: "2024-10-23",
    location: "Paris (FR)",
  },
  {
    id: 11,
    venue: "TBA",
    date: "2024-10-24",
    location: "Brussels (BE)",
  },
  {
    id: 12,
    venue: "OCCII",
    date: "2024-10-25",
    location: "Amsterdam (NL)",
  },
  {
    id: 13,
    venue: "Privat",
    date: "2024-10-26",
    location: "Cologne (BE)",
  },
  {
    id: 14,
    venue: "Juz",
    date: "2024-10-27",
    location: "Mannheim (DE)",
  },
  {
    id: 15,
    venue: "Blechschloss",
    date: "2024-10-29",
    location: "Dresden (DE)",
  },
  {
    id: 16,
    venue: "Schokoladen",
    date: "2024-10-30",
    location: "Berlin (DE)",
  },
  {
    id: 17,
    venue: "The Canal Club",
    date: "2024-11-02",
    location: "Richmond, VA (US)",
  },
  {
    id: 18,
    venue: "TV EYE",
    date: "2025-02-07",
    location: "New York, NY",
  },
  {
    id: 19,
    venue: "Bar Bad Ending",
    date: "2025-02-08",
    location: "Rochester, NY",
  },
  {
    id: 20,
    venue: "Foto Club",
    date: "2025-02-09",
    location: "Philadelphia, PA",
  },
  {
    id: 21,
    venue: "Banditos",
    date: "2025-02-10",
    location: "Richmond, VA",
  },
  {
    id: 22,
    venue: "The Dome",
    date: "2025-06-07",
    location: "Virginia Beach, VA",
  },
  {
    id: 23,
    venue: "The Fillmore Silver Spring",
    date: "2025-06-09",
    location: "Silver Spring, MD",
  },
  {
    id: 24,
    venue: "The Fillmore Philadelphia",
    date: "2025-06-10",
    location: "Philadelphia, PA",
  },
  {
    id: 25,
    venue: "House of Blues",
    date: "2025-06-11",
    location: "Boston, MA",
  },
  {
    id: 26,
    venue: "Brooklyn Paramount",
    date: "2025-06-12",
    location: "New York, NY",
  },
  {
    id: 27,
    venue: "Brooklyn Paramount",
    date: "2025-06-13",
    location: "New York, NY",
  },
  {
    id: 28,
    venue: "Paramount Theater",
    date: "2025-06-14",
    location: "Huntington, NY",
  },
];
